### ISSUE TITLE
YoduPlayer 配置生成器不能生成歌单全部歌曲

### ISSUE THREAD

**Issue by ChirmyRam** [vcheckzen/LanzouCloudAPI#1]
最近发现YoduPlayer配置生成器生成歌单的配置一次只能生成十首歌，无法生成歌单中的所有歌曲，我自己在腾讯云函数上面部利用此源码署了api也是这样，请问有没有解决办法？
谢谢。

**Comment by vcheckzen** [comment]
网易云加了限制，用最新代码重新部署
