### ISSUE TITLE
大佬，麻烦查一下。或许真有问题？

### ISSUE THREAD

**Issue by renwfy** [vcheckzen/LanzouCloudAPI#11]
我下载最新代码，本地跑起来，代码里面测试的链接一直loading没结果……

我用真实的链接也是一直请求，没结果……

<img width="692" alt="image" src="https://github.com/user-attachments/assets/e4324761-b42b-4825-8144-81074fb59acb">

**Comment by vcheckzen** [comment]
我测试正常，你看蓝奏云哪个地址在你那能打开，换到代码里
https://github.com/vcheckzen/LanzouCloudAPI/blob/6e2f4d1bff68353193262ea2c3dee335dfa1779e/index.py#L15

**Comment by renwfy** [comment]
我重新部署了下，可以了。感谢！！
