### ISSUE TITLE
这个链接不能获取到呢

### ISSUE THREAD

**Issue by yssmile** [vcheckzen/LanzouCloudAPI#4]
https://dkbd.lanzoui.com/dkbdv7

**Comment by vcheckzen** [comment]
没专门处理自定义页面，你可以再提交几个有密码和无密码的自定义界面，我一起加上

**Comment by vcheckzen** [comment]
不过你这个链接，把下面的 7 改成 6 或者以下的数字就行了。

https://github.com/vcheckzen/LanzouCloudAPI/blob/9cc4edadd559cce5c4dc545877e7b42578c9e4bb/index.py#L119

**Comment by yssmile** [comment]
https://xhkt006.lanzoux.com/b00noblxi
https://dkbd.lanzoui.com/feifei1
密码：aam1
